Repository newrelic/infra-integrations-sdk, pull requests merged in 2018-07, with the labels that each got.

#115 Add steps to migrate from v2 to v3
  docs/v2tov3.md
Labels: risk:low

#119 Delete misleading comment + use arguments
  docs/tutorial-code/single-entity/redis.go
  docs/tutorial.md
Labels: risk:low

#117 Reduce JMX memory allocation
  jmx/jmx.go
Labels: risk:low

#122 Remove obsolete returned errors
  data/metric/metrics.go
  data/metric/metrics_test.go
  docs/tutorial-code/multiple-entities/redis-multi.go
  docs/tutorial-code/single-entity/redis.go
  integration/entity.go
  integration/integration_test.go
Labels: risk:low

#121 Remove TODOs
  .gometalinter.json
  Makefile
  args/json.go
  persist/storer.go
Labels: risk:low

#124 Changelog 3.0.1
  CHANGELOG.md
Labels: risk:low

#125 Fix example error
  docs/toolset/integration.md
Labels: risk:low

#126 Fix readme go get
  README.md
Labels: bug

#127 Doc for RATE & DELTA required attribute/s
  docs/toolset/integration.md
Labels: risk:low

#128 Fix JMX flush warnings
  jmx/jmx.go
Labels: bug, risk:low

#129 Fix JMX race on wait
  jmx/jmx.go
Labels: bug, risk:low
