Repository newrelic/infra-integrations-sdk, pull requests merged in 2018-05, with the labels that each got.

#74 Documented: Upgrading from GoSDK v2.x to GoSDK v3
  docs/images/src/v1vsv2.graphviz
  docs/images/v1vsv2.png
  docs/v2tov3.md
Labels: risk:low

#77 Doc protocol compatibility
  README.md
Labels: risk:low

#79 Update v2tov3.md
  docs/v2tov3.md
Labels: risk:low

#80 Remove tutorial obsolete v1 dep
  docs/tutorial-code/redis.go
Labels: risk:low

#82 Add go 1.10 version
  .travis.yml
Labels: risk:low

#85 Fixed inventory JSON marshaling
  data/inventory/inventory.go
  integration/integration_test.go
Labels: bug, risk:low

#84 Exmplain how to declare arguments
  docs/tutorial.md
Labels: risk:low

#81 Store all types
  data/metric/metrics.go
  data/metric/metrics_test.go
  integration/options_test.go
  persist/storer.go
  persist/storer_test.go
Labels: enhancement, risk:low

#78 Fix JMX race conditions
  integration/entity.go
  integration/integration.go
  jmx/jmx.go
  jmx/jmx_test.go
  persist/storer.go
Labels: help wanted, risk:low

#86 Fix tutorial confusing parts
  data/inventory/inventory.go
  docs/tutorial.md
  integration/entity.go
Labels: risk:low

#87 explain how to use DefaultArgumentList.
  docs/tutorial.md
Labels: risk:low

#90 Best practices
  docs/tutorial.md
Labels: risk:low

#89 Doc on remote entities
  README.md
Labels: risk:low

#94 Restore skipped args tests
  args/args_test.go
Labels: risk:low

#93 Rhervas/jmx errors
  jmx/jmx.go
  jmx/jmx_test.go
Labels: risk:low

#95 Convert Gauge to float
  data/metric/metrics.go
  data/metric/metrics_test.go
Labels: risk:low

#83 Http client wrapper
  args/args.go
  http/client.go
  http/client_test.go
Labels: risk:low

#88 Limit inventory key length
  data/inventory/inventory.go
  data/inventory/inventory_test.go
  docs/tutorial-code/redis.go
  integration/entity.go
  integration/entity_test.go
  integration/integration_test.go
Labels: risk:low

#92 Using a new Storer that allows unmarshalling into structs
  data/metric/metrics.go
  data/metric/metrics_test.go
  integration/integration.go
  integration/options_test.go
  persist/storer.go
  persist/storer_test.go
Labels: risk:low

#96 Documenting persistence and logger
  docs/toolset/README.md
  docs/toolset/examples/persist.go
  docs/toolset/log.md
  docs/toolset/persist.md
  log/log.go
Labels: risk:low

#102 Test default arguments without struct embedding
  args/args_test.go
Labels: risk:low

#99 Integration documents
  docs/README.md
  docs/toolset/README.md
  docs/toolset/args.md
  docs/toolset/integration.md
Labels: risk:low

#100 Documented http helper library
  docs/toolset/README.md
  docs/toolset/http.md
  http/client.go
Labels: risk:low

#101 Documented JMX library
  docs/toolset/README.md
  docs/toolset/jmx.md
Labels: risk:low

#104 Remove All flag
  args/args.go
  args/args_test.go
  docs/toolset/examples/persist.go
  docs/tutorial-code/redis.go
  docs/tutorial.md
  integration/integration_test.go
Labels: risk:low

#103 Documented arguments' API
  README.md
  docs/toolset/args.md
Labels: risk:low
