Repository newrelic/infra-integrations-sdk, pull requests merged in 2018-06, with the labels that each got.

#105 Faqs
  README.md
Labels: risk:low

#108 Fixed documentation link
  docs/toolset/README.md
Labels: risk:low

#106 Cache collision fix
  data/metric/metrics.go
  data/metric/metrics_test.go
  integration/entity.go
  persist/storer.go
  persist/storer_test.go
Labels: bug, risk:medium

#109 Fixed nil pointer when creating an entity
  CHANGELOG.md
  integration/integration.go
  integration/integration_test.go
Labels: bug, risk:low

#113 Fix debug mode for default logger
  integration/integration.go
  integration/integration_test.go
Labels: bug, risk:low

#110 Allow negative rate & deltas
  data/metric/metrics.go
  data/metric/metrics_test.go
Labels: bug, risk:low

#112 Cli-arguments override Env vars
  args/args.go
  args/args_test.go
Labels: risk:low

#111 Remove non-concurrency support
  CHANGELOG.md
  docs/toolset/integration.md
  docs/v2tov3.md
  integration/entity.go
  integration/entity_test.go
  integration/integration.go
  integration/options.go
  integration/options_test.go
Labels: risk:low

#114 Restore and deprecate global logger
  docs/toolset/log.md
  docs/v2tov3.md
  integration/integration.go
  log/log.go
  log/log_test.go
Labels: risk:low
