Repository newrelic/infra-integrations-sdk, pull requests merged in 2018-04, with the labels that each got.

#49 Merging v3 branch and master
  CHANGELOG.md
  docs/images/redis_event_notifications_view.png
  docs/images/redis_event_redis-server_view.png
  docs/tutorial-code/myorg-redis-config.yml
  docs/tutorial-code/myorg-redis-definition.yml
  docs/tutorial-code/redis.go
  docs/tutorial.md
  log/log.go
  log/log_test.go
  metric/metrics_test.go
  sdk/data.go
  sdk/data_test.go
  sdk/protocol2.go
  sdk/protocol2_test.go
Labels: risk:high

#55 Minor logging corrections
  args/args.go
  args/json.go
  cache/cache.go
  docs/tutorial-code/redis.go
  jmx/jmx.go
  log/log.go
  metric/metrics.go
  sdk/data.go
Labels: risk:low

#54 Moar linting
  cache/cache.go
  cache/cache_test.go
  metric/metrics.go
  metric/metrics_test.go
  sdk/v1/data_test.go
  sdk/v2/data_test.go
Labels: enhancement, risk:low

#52 Renaming and tests integration v2 events
  .gometalinter.json
  Makefile
  args/args.go
  args/json.go
  cache/cache.go
  cache/cache_test.go
  docs/tutorial-code/redis.go
  jmx/jmx.go
  log/log.go
  metric/metrics.go
  metric/metrics_test.go
  sdk/v1/data.go
  sdk/v1/data_test.go
  sdk/v2/data.go
  sdk/v2/data_test.go
Labels: risk:low

#51 Different packages for different protocol versions
  .gometalinter.json
  Makefile
  args/args.go
  args/json.go
  cache/cache.go
  cache/cache_test.go
  docs/tutorial-code/redis.go
  jmx/jmx.go
  log/log.go
  metric/metrics.go
  metric/metrics_test.go
  sdk/v1/data.go
  sdk/v1/data_test.go
  sdk/v2/data.go
  sdk/v2/data_test.go
Labels: risk:low

#58 Updated changelog with latest breaking change
  CHANGELOG.md
  args/json.go
  sdk/v2/data.go
Labels: risk:low

#60 Decouple logger
  cache/cache.go
  cache/cache_test.go
  cache/global.go
  docs/tutorial-code/redis.go
  log/log.go
  log/log_test.go
  sdk/v1/data.go
  sdk/v2/data.go
Labels: enhancement, risk:low

#57 Supress make echoes
  Makefile
Labels: enhancement, risk:low

#61 Improved cache API
  cache/cache.go
  cache/cache_test.go
  cache/global.go
  docs/tutorial-code/redis.go
  log/log.go
  metric/metrics.go
  metric/metrics_test.go
  persist/global.go
  persist/global_test.go
  persist/storer.go
  persist/storer_test.go
  sdk/v1/data.go
  sdk/v2/builder.go
  sdk/v2/builder_test.go
  sdk/v2/data.go
Labels: risk:low

#63 Enhance data serializer
  sdk/v2/data.go
Labels: enhancement, risk:low

#65 Removed V1 Payload support
  .gometalinter.json
  Makefile
  sdk/builder.go
  sdk/builder_test.go
  sdk/data.go
  sdk/data_test.go
  sdk/v1/data.go
  sdk/v1/data_test.go
Labels: risk:low

#66 Removed global cache
  log/log.go
  metric/metrics.go
  metric/metrics_test.go
  persist/global.go
  persist/global_test.go
  persist/storer.go
  persist/storer_test.go
  sdk/builder.go
  sdk/builder_test.go
  sdk/data.go
Labels: risk:low

#68 Updated CHANGELOG with 2.1.0 release CHANGELOG
  CHANGELOG.md
Labels: risk:low

#67 Change public api
  Makefile
  docs/tutorial-code/redis.go
  integration/builder.go
  integration/builder_test.go
  integration/entity.go
  integration/entity_test.go
  integration/integration.go
  integration/integration_test.go
  metric/event.go
  metric/inventory.go
  metric/metrics.go
  metric/metrics_test.go
  persist/storer.go
  persist/storer_test.go
  sdk/builder.go
  sdk/data.go
Labels: risk:medium

#72 Integration creation using functional options
  integration/builder.go
  integration/builder_test.go
  integration/entity.go
  integration/entity_test.go
  integration/integration.go
  integration/integration_test.go
  integration/options.go
  integration/options_test.go
Labels: risk:low

#71 Code review
  integration/builder.go
  integration/builder_test.go
  integration/entity.go
  integration/entity_test.go
  integration/integration.go
  integration/integration_test.go
  integration/options.go
  integration/options_test.go
  log/log_test.go
  metric/event_test.go
  metric/inventory_test.go
  metric/metrics_test.go
  persist/storer.go
  persist/storer_test.go
Labels: risk:low

#73 Data packages + LocalEntity
  data/event/event.go
  data/event/event_test.go
  data/inventory/inventory.go
  data/inventory/inventory_test.go
  data/metric/metrics.go
  data/metric/metrics_test.go
  docs/tutorial-code/redis.go
  integration/entity.go
  integration/entity_test.go
  integration/integration.go
  integration/integration_test.go
Labels: risk:low

#75 Changelog v3
  CHANGELOG.md
Labels: enhancement, risk:low

#76 Rename Type for Namespace
  integration/entity.go
  integration/entity_test.go
  integration/integration.go
Labels: risk:low
