Repository newrelic/infra-integrations-sdk, pull requests merged in 2019-11, with the labels that each got.

#191 Remove JMX lock
  CHANGELOG.md
  jmx/jmx.go
Labels: enhancement, risk:medium

#192 JMX: remove line length limitation
  CHANGELOG.md
  jmx/jmx.go
Labels: enhancement, risk:medium

#195 Jmx avoid stderr closed err
  jmx/jmx.go
Labels: enhancement, risk:low

#190 jmx multiline support
  CHANGELOG.md
  jmx/jmx.go
  jmx/jmx_test.go
Labels: bug, risk:medium

#194 JMX: custom nrjmx exec option + remove stderr closed
  CHANGELOG.md
  jmx/jmx.go
  jmx/jmx_test.go
Labels: enhancement, risk:low

#196 Fix jmx warning handling
  CHANGELOG.md
  jmx/jmx.go
  jmx/jmx_test.go
Labels: bug, risk:medium

#197 JMX full connection URL
  jmx/jmx.go
  jmx/jmx_test.go
Labels: enhancement, risk:low

#198 Fix jmx connection URL option
  jmx/jmx.go
Labels: bug, risk:low

#199 JMX add user&pass when using conn URL
  jmx/jmx.go
Labels: risk:low

#200 JMX restore auto close on timeout or empty line
  jmx/jmx.go
Labels: risk:low

#201 JMX improve connection error handling
  jmx/jmx.go
Labels: enhancement, risk:low

#202 JMX restore single nrjmx line ingest
  CHANGELOG.md
  jmx/jmx.go
  jmx/jmx_test.go
Labels: enhancement, risk:low

#204 Test showing metric value overwriting behaviour
  data/metric/metrics_test.go
Labels: enhancement, risk:low

#187 Enable custom attributes for events
  CHANGELOG.md
  data/attribute/attribute.go
  data/event/event.go
  data/event/event_test.go
  data/metric/metrics.go
  data/metric/metrics_test.go
  data/metric/set_marshal_test.go
  docs/entity-definition.md
  integration/entity.go
  integration/entity_test.go
  integration/integration_test.go
Labels: risk:medium
