Repository newrelic/infra-integrations-sdk, pull requests merged in 2020-04, with the labels that each got.

#221 Update Go versions support
  .travis.yml
Labels: enhancement, risk:low

#213 add document on how to migrate from v3
  docs/v3tov4.md
Labels: WIP

#220 http client accepting invalid hostnames
  .travis.yml
  CHANGELOG.md
  http/client.go
  http/client_test.go
Labels: enhancement, risk:medium
